name: Build and Package on PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish project
        run: >
          dotnet publish -c Release -r win-x64 --self-contained true
          /p:PublishSingleFile=true
          /p:IncludeNativeLibrariesForSelfExtract=true
          /p:PublishTrimmed=false
          -o ./publish

      - name: Install Inno Setup
        run: choco install innosetup --no-progress

      - name: Build the installer
        run: iscc installer.iss

      - name: Upload installer as artifact
        uses: actions/upload-artifact@v4
        with:
          name: sentinel-setup
          path: Sentinel_*.exe
